#############  {key}  , {key} ##############3
encrypt:
  key: "54io4no4n5op34nio4n35ion4foasnd,asndindgoinonfdiofnio"

jwt:
  key: "Q7q74DpXkmRQgangVx3Z4BwL5MPJDr6G"

database:
  host: "localhost"
  database: "science"
  username: "ctreminio"
  password: "ctreminio"
  port: 5432
  ssl: "disable"
