


# Training Hyperparams --------------------------------------
database:
  host: "ec2-18-188-250-148.us-east-2.compute.amazonaws.com"
  database: "science"
  username: "ctreminio"
  password: "ctreminio"
  port: 5432
  ssl: "disable"


aes:
  key: "Q7q74DpXkmRQgangVx3Z4BwL5MPJDr6G"

