database:
  host: "ec2-18-188-250-148.us-east-2.compute.amazonaws.com"
  database: "science"
  username: "ctreminio"
  password: "ctreminio"
  port: 5432
  ssl: "disable"

aes:
  key: "@@$^Ze4s84t$"K&t&J+P;+/HFq4r9eqn"